# Generated by Django 4.2.7 on 2025-09-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_prescription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hasProfile',
            field=models.BooleanField(default=False),
        ),
    ]
