# Generated by Django 4.2.7 on 2025-09-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_prescription', '0002_user_hasprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
