# Generated by Django 4.2.7 on 2025-09-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_prescription', '0006_remove_doctor_id_alter_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
