# Generated by Django 4.2.7 on 2025-09-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_prescription', '0008_alter_user_is_phone_verified_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyrecommendation',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
