# Generated by Django 4.2.7 on 2025-09-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_prescription', '0009_pharmacyrecommendation_is_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyrecommendation',
            name='is_ordered',
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
