# Generated by Django 4.2.7 on 2026-05-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_prescription', '0012_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='drug_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Drug Name'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
