# Generated by Django 4.2.7 on 2026-05-23 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_prescription', '0014_alter_prescriptionitem_drug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_prescription.drug'),
        ),
    ]
